### ISSUE TITLE
Let editors insert inline buttons which pop up a modal window containing a rich text field

### ISSUE THREAD

**Issue by alexgleason** [ProjectTIER/projecttier.org#79]
For various reasons, sometimes there is content that may pertain to only some readers, or is tangential to the topic at hand. We want the ability to create a special link that readers can click to pop up a modal window with this information.

The link should not look like a normal hyperlink, but not like a button either. Here's an example of what it could look like:

---

![screenshot from 2018-11-13 15 25 33](https://user-images.githubusercontent.com/3639540/48441002-6ad0b080-e758-11e8-8b53-a3c3faebcd01.png)

```css
.modal-link {
    background: #1d7ac9;
    padding: 1px 5px;
    border-radius: 9999px;
    color: white;
}
.modal-link::before {
    content: '🛈';
    margin-right: 3px;
    transform: translateY(-1px);
    display: inline-block;
}
```

---

Clicking it should pop up a modal, similar to one of these:

![screenshot from 2018-11-13 15 27 45](https://user-images.githubusercontent.com/3639540/48441109-b2573c80-e758-11e8-8955-45f5a57bc92e.png)

This is a [Foundation 6 *Reveal*](https://foundation.zurb.com/sites/docs/reveal.html).

---

This needs to be represented somehow in the Wagtail page editor. This is possible by [extending Draftail (Wagtail 2.3 docs)](https://docs.wagtail.io/en/v2.3/advanced_topics/customisation/extending_draftail.html) to include a new button. That button should pop-up a custom [Modal Workflow](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/static_src/wagtailadmin/js/modal-workflow.js), which lets us configure the link and enter rich text, then it gets saved into the editor.

We'll also likely need to write a templatetag or filter to render it on the page.
